version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rwoods/fantasypayandplay
    container_name: fantasypayandplay
    ports:
      - "3000:5000"
    env_file:
      - .env